## 파이토치(PyTorch) 프레임워크란?
- 파이토치(PyTorch)는 메타에서 개발한 파이썬 기반 오픈소스 딥러닝 프레임워크로, GPU 병렬 연산과 자동 미분 기능을 제공합니다.  
실행 시점에 그래프가 결정되는 동적 계산 방식을 채택해 복잡한 조건문과 반복문 구조도 제약 없이 유연하게 처리할 수 있습니다.  
파이썬 고유의 직관적인 코드 작성 방식을 지원하므로 디버깅과 수정이 용이하며 전체적인 모델 연구 및 개발 속도를 획기적으로 줄여줍니다.

- 즉, 머신러닝 딥러닝을 만들 수 있는 개발 환경입니다. 현업 파이토치8: 텐서플로우2


[파이토치 공식문서](https://docs.pytorch.org/docs/2.14/index.html)

## . 스칼라(Scalar)
- 스칼라는 정수나 실수처럼 단 하나의 숫자만을 표현하는 가장 기본적인 자료형입니다.  
  파이토치에서는 이 스칼라를 차원이 존재하지 않는 0차원 텐서 형태로 다룹니다.

In [1]:
import torch
import numpy as np

In [2]:
num1 = torch.tensor(10)
num2 = torch.tensor(1.5)
print(type(num1))
print(type(num2))
# tensor : 자료형 (자료형이 그냥 tensor)

<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [3]:
# s = torch.tensor("단비")
# print(s)

### 모델은 컴퓨터를 학습시키는 것을 의미하며, 학습은 모두 숫자형으로만 가능하다. 즉 tensor는 숫자 자료형밖에 넣을 수 없다.

In [4]:
num3 = torch.tensor([10], dtype=torch.float64)
print(num3)

tensor([10.], dtype=torch.float64)


In [5]:
num4 = torch.tensor([20], dtype=torch.int64)
print(num4)

tensor([20])


In [6]:
num5 = torch.tensor([20], dtype=torch.long)
print(num5)

tensor([20])


In [7]:
num6 = torch.tensor([[60]])
print(num6)

tensor([[60]])


In [8]:
num3 + 10

tensor([20.], dtype=torch.float64)

In [9]:
# 텐서 자료형을 꺼내오고싶다면? item 이라는 메소드 이용

## .item()
- 텐서 자료형에서 값을 꺼내오는 메서드

In [10]:
num3.item()

10.0

## 텐서간의 연산

In [11]:
print(num1)
print(num2)

print(num1 + num2)

tensor(10)
tensor(1.5000)
tensor(11.5000)


In [12]:
print(num1)
print(num3)

print(num1 + num3) # 1차원

tensor(10)
tensor([10.], dtype=torch.float64)
tensor([20.], dtype=torch.float64)


In [13]:
print(num1)
print(num6)

print(num1 + num6) # 2차원

tensor(10)
tensor([[60]])
tensor([[70]])


### 0차원 값과 다차원 값을 연산하면 다차원 값으로 반환한다. ex) 0차원 + 2차원 = 2차원

## 2) 백터(Vector)
- 하나 이상의 원소가 일렬로 나열된 1차원 텐서 형태의 자료구조를 의미합니다.
- 파이토치에서는 n의 원소가 담긴 벡터는 (n, )형태의 차원을 갖게 됩니다.

In [14]:
v1 = torch.tensor([1.0, 2.0, 3.0])
v2 = torch.tensor([10.0, 20.0, 30.0])

In [15]:
print(v1)
print(v2)

print(v2.shape)
print(v2.size())

tensor([1., 2., 3.])
tensor([10., 20., 30.])
torch.Size([3])
torch.Size([3])


In [16]:
print(v1 + num1)
# 브로드캐스팅이 가능

tensor([11., 12., 13.])


In [17]:
print(v1 + v2)

tensor([11., 22., 33.])


## 행렬(Matrix)
- 행과 열로 이루어진 2차원의 형태의 텐서를 의미한다. 예를 들어 2행 2열의 데이터라면 torch.tensor([[1,2], [3,4]])로 표기되며 행렬곱 연산이 가능합니다. 파이토치에서 행렬 연산은 torch.mm함수나 @연산자로 간편하게 수행할 수 있습니다.
- (np.matmul()) -> mm

In [18]:
mt1 = torch.tensor([[1,2], [3,4]])
mt2 = torch.tensor([[10,20], [30,40]])

print(mt1)
print(type(mt1))
print(mt1.shape)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.Size([2, 2])


In [19]:
print(mt1 + num1)
print(mt1 + mt2)

tensor([[11, 12],
        [13, 14]])
tensor([[11, 22],
        [33, 44]])


In [20]:
# print(mt1 + v1) # 이건 안댐 열의 개수가 달라서

In [21]:
print(mt1 + torch.tensor([100,200])) # 이건되는가? yes 차원이 다른건 ㄱㅊ 2차원으로 계산되심 ㅋㅋ!
# 차원은 달라도 상관이 없으나, 열의 개수가 다르면 연산할 수 없다.

tensor([[101, 202],
        [103, 204]])


## 4) 텐서

In [22]:
data = [
    [1, 2],
    [3, 4]
]

t1 = torch.tensor(data)
print(t1)

tensor([[1, 2],
        [3, 4]])


In [23]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

### tensor -> ndarry

In [24]:
print(t1)
print(type(t1))

print(t1.numpy())
print(type(t1.numpy()))

# 두개의 결과는 다르게 출력됨!

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [25]:
ndarray1 = np.array([10, 20, 30])
ndarray1

print(ndarray1)
print(torch.from_numpy(ndarray1))

[10 20 30]
tensor([10, 20, 30])


In [26]:
t3 = torch.tensor([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [5, 6, 7, 8]
])

print(t3)
print(t3.size())
print(t3[1]) #행으로 가져오기 : 인덱싱!!
#텐서는 인덱싱도 가능하다!!!!!!!!!

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 5,  6,  7,  8]])
torch.Size([3, 4])
tensor([10, 20, 30, 40])


In [27]:
print(t3[1:2])
# 슬라이싱도 가넝!!!!!!!!!!!

tensor([[10, 20, 30, 40]])


In [28]:
print(t3)
print(t3[:, 0])
# 모든 행의 마지막 열의 0번 가져온것

tensor([[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 5,  6,  7,  8]])
tensor([ 1, 10,  5])


In [29]:
print(t3[..., 0])
# 다차원일때 앞의차원 싹 다 가져온다음 0번째 가져올수도있음!! (지금 이건 다차원이 아니라 ㅎ..)

tensor([ 1, 10,  5])


In [30]:
t4 = np.arange(1, 13).reshape(2, 2, 3)
# 3차원으로 나누기

t4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
t4 = np.arange(1, 13).reshape(2, -1, 3)
t4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
t5 = torch.from_numpy(t4)
t5
# 텐서형으로 자료형이 바뀌어서 내려오밍

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [33]:
print(t5[:, 0])

tensor([[1, 2, 3],
        [7, 8, 9]])


In [34]:
print(t5[..., 0])

tensor([[ 1,  4],
        [ 7, 10]])


## 5) 행렬곱

In [35]:
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([1, 2, 3])

print(v1)
print(v2)

tensor([1, 2, 3])
tensor([1, 2, 3])


In [36]:
print(torch.matmul(v1, v2))

tensor(14)


## 내적(Dot Product) 계산 및 개념

### 개념
- 내적은 두 벡터 간의 원소별 곱을 모두 더하는 연산으로, 두 벡터가 얼마나 같은 방향을 향하는지 나타내는 유사도(방향성 일치도)의 척도입니다.

### 내적 공식
3차원 벡터 A = (x1, y1, z1)와 B = (x2, y2, z2)의 내적 공식은 다음과 같습니다.

A · B = x1*x2 + y1*y2 + z1*z3

- 첫 번째 성분끼리 곱하기: 1 x 11 = 11
- 두 번째 성분끼리 곱하기: 2 x 12 = 24
- 세 번째 성분끼리 곱하기: 3 x 13 = 39
- 최종 내적 값: 11 + 24 + 39 = 74 (0차원 스칼라)

### 내적과 행렬곱의 관계
1차원, 2차원, 3차원 텐서 모두 행렬곱 연산이 가능하며, 행렬곱의 결과 형태(Shape)는 입력되는 행렬들의 크기에 따라 다르게 결정됩니다. 행렬곱을 이루는 각 위치의 원소를 계산하는 본질적인 연산 방식이 바로 벡터의 내적이며, (1, n) 행렬과 (n, 1) 행렬의 곱처럼 결과가 1x1 형태의 2차원 행렬로 나오는 경우 그 내부 원소 값은 두 벡터의 내적 값(0차원 스칼라)과 동일합니다.

In [37]:
"""
    1차원 벡터 내적 [1, 2, 3] x [1, 2, 3]
    (3,) 크기를 가지는 1차원 벡터 2개의 내적 연산 과정입니다.

    - 첫 번째 성분끼리 곱하기: 1 x 1 = 1
    - 두 번째 성분끼리 곱하기: 2 x 2 = 4
    - 세 번째 성분끼리 곱하기: 3 x 3 = 9
    - 최종 연산 결과: 1 + 4 + 9 = 14
"""

None

In [38]:
v3 = torch.tensor([[1, 2, 3]])
v4 = torch.tensor([[1],[2],[3]])

print(v3)
print(v4)

print(v3.shape)
print(v4.shape)

print(torch.mm(v3, v4))

# ㅈㅉ 뭔소린지 뭐하는지 모르겠서요

tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
torch.Size([1, 3])
torch.Size([3, 1])
tensor([[14]])


In [39]:
m3 = torch.tensor([[1, 2], [3, 4]])
m4 = torch.tensor([[5, 6], [7, 8]])

print(m3)
print(m4)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [40]:
print(torch.mm(m3, m4))

tensor([[19, 22],
        [43, 50]])


In [41]:
"""
    2x2 행렬곱 [[1, 2], [3, 4]] x [[5, 6],
                                 [7, 8]]

    - 첫 번째 행 × 첫 번째 열:
      1 x 5 + 2 x 7 = 19

    - 첫 번째 행 × 두 번째 열:
      1 x 6 + 2 x 8 = 22

    - 두 번째 행 × 첫 번째 열:
      3 x 5 + 4 x 7 = 43

    - 두 번째 행 × 두 번째 열:
      3 x 6 + 4 x 8 = 50

    - 최종 연산 결과:
      [[19, 22], [43, 50]]

      내적이 클수록 → 같은 방향에 가까움
      내적이 작을수록 → 같은 반대에 가까움
"""

None

### 참고. 유클리드 거리 (Euclidean Distance)
- 두 벡터 `A`, `B` 사이의 거리를 구하는 공식입니다.
- 유클리드 거리 = 각 차이를 제곱 → 전부 더하기 → 제곱근

$$
d(A,B) = \sqrt{\sum_{i=1}^{n}(A_i-B_i)^2}
$$

2차원 벡터라면:

$$
d(A,B) = \sqrt{(A_1-B_1)^2+(A_2-B_2)^2}
$$

예시:

$$
A=(1,2), \quad B=(3,4)
$$

$$
d(A,B)
= \sqrt{(1-3)^2+(2-4)^2}
$$

$$
= \sqrt{(-2)^2+(-2)^2}
$$

$$
= \sqrt{4+4}
$$

$$
= \sqrt{8}
\approx 2.83
$$

In [42]:
## 와~~~~~~~~~~~~~~~ 이게 뭔소리임

In [43]:
a = torch.tensor([1, 2], dtype=torch.float32)
b = torch.tensor([3, 4], dtype=torch.float32)

diff = a - b
print(diff)

# 뭘 구하기 위해서?? norm???
distance = torch.norm(diff)
print(distance)
# 요 내적과 같은 방향으로 가는걸ㄹ수록?? 유사한??? 
# 거리와 벡터의 방향 거리를 구해ㅔ서?? 유사한걸 구하는???
# 내가 할건 아니고 컴터가 알아서 하긴할건데 원리를 알면 좋겟지... 근데 난 못알아듣겠지....

tensor([-2., -2.])
tensor(2.8284)


## 파이토치의 핵심 장점: GPU 활용과 연산 가속
- GPU(Graphics Processing Unit)는 본래 이미지 렌더링과 같은 대규모 병렬 계산을 처리하기 위해 설계된 그래픽 처리 장치입니다. 하지만 최근에는 수많은 행렬 및 벡터 연산이 필요한 인공지능(AI)과 딥러닝 분야에서 뛰어난 연산 가속기로 널리 활용되고 있습니다. GPU는 다수의 코어를 통해 수천, 수만 개의 연산을 동시에 병렬로 처리할 수 있는 구조를 갖추고 있어 딥러닝 모델 학습에 매우 최적화되어 있습니다.
- 파이토치에서 이러한 GPU 가속을 활용하기 위해서는 외장 그래픽카드와 함께 전용 하드웨어 설치 프로그램(예: NVIDIA CUDA 등)을 갖추어야 하며, 내장 그래픽 환경에서는 사용이 불가능합니다. 만약 로컬에 적합한 그래픽 카드가 없는 경우, 구글 코랩(Google Colab) 환경을 이용하면 무료로 GPU 가속을 사용해 볼 수 있습니다.
- 한편, 머신러닝과 딥러닝 전용으로 개발된 또 다른 가속 장치인 TPU(Tensor Processing Unit)의 경우, 본래 텐서플로(TensorFlow) 환경에 최적화되어 있어 파이토치에서는 직접적인 사용 및 적용이 다소 제한적입니다. 따라서 파이토치를 활용한 딥러닝 연산 시에는 GPU 환경을 구축하고 사용하는 것이 가장 일반적이고 효율적인 방법입니다.

In [44]:
print("Cuda(NVIDIA) 사용 가능 여부:", torch.cuda.is_available())
print("Mps 사용 가능 여부:", torch.mps.is_available())
print("Cpu 사용 가능 여부:", torch.cpu.is_available())
print("Xpu(Intel 내장그래픽) 사용 가능 여부:", torch.cpu.is_available())
# 외장그래픽 있는 사람은 사용 가능

Cuda(NVIDIA) 사용 가능 여부: True
Mps 사용 가능 여부: False
Cpu 사용 가능 여부: True
Xpu(Intel 내장그래픽) 사용 가능 여부: True


In [46]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.mps.is_available():
    device = torch.device("mps")
elif torch.xpu.is_available():
    device = torch.device("xpu")
else:
    device = torch.device("cpu")

print(f"현재 선택된 장치: {device}")

현재 선택된 장치: cuda


In [49]:
t1 = torch.tensor([10])

#.to()
t1_gpu = t1.to(device)

print(t1)
print(t1_gpu)

#gpu와 cpu의 공간이 다르기때문에 연산이 안됨
# print(t1 + t1_gpu)

tensor([10])
tensor([10], device='cuda:0')


In [53]:
print(t1.is_cpu)
print(t1_gpu.is_cpu)
print(t1_gpu.is_cuda)
print(t1_gpu.is_xpu)

True
False
True
False


In [54]:
t2 = torch.tensor([[1,2], [3,4]])
t3 = torch.tensor([[10,20], [30,40]])

t2_gpu = t2.to(device)
t3_gpu = t3.to(device)

In [55]:
print(t2_gpu + t3_gpu)
print(t2_gpu * t3_gpu)
print(t2_gpu / t3_gpu)
print(t2_gpu - t3_gpu)

tensor([[11, 22],
        [33, 44]], device='cuda:0')
tensor([[ 10,  40],
        [ 90, 160]], device='cuda:0')
tensor([[0.1000, 0.1000],
        [0.1000, 0.1000]], device='cuda:0')
tensor([[ -9, -18],
        [-27, -36]], device='cuda:0')


In [65]:
# print(t2_gpu.mean())
# 기본타입이 정수타입이라 못구한다???엥

#sum은 가능
print(t2_gpu.sum())
print(t2_gpu.sum(dim=0))
print(t2_gpu.sum(dim=1))
# 열끼리 더한거임 : dim

tensor(10, device='cuda:0')
tensor([4, 6], device='cuda:0')
tensor([3, 7], device='cuda:0')


In [66]:
# .to() : 자료형을 변경할 수도 있다.
t4 = t3_gpu.to(torch.float32)
print(t4)
print(t4.mean())
print(t4.mean(dim=0))
print(t4.mean(dim=1))

tensor([[10., 20.],
        [30., 40.]], device='cuda:0')
tensor(25., device='cuda:0')
tensor([20., 30.], device='cuda:0')
tensor([15., 35.], device='cuda:0')


In [67]:
print(t4.max())
print(t4.min())

tensor(40., device='cuda:0')
tensor(10., device='cuda:0')


In [70]:
print(t4) # 여기서 가장 큰 값의 인덱스를 구하고싶다면?
print(t4.argmax(dim=1))
#작은값?
print(t4.argmin())

tensor([[10., 20.],
        [30., 40.]], device='cuda:0')
tensor([1, 1], device='cuda:0')
tensor(0, device='cuda:0')


In [73]:
# .flatte(): 평탄화
print(torch.flatten(t4))
torch.flatten(t4).argmax()
# 데이터를 일렬로 쫙 펼침? 그중에 가장 큰 값 가져오게끔..???

tensor([10., 20., 30., 40.], device='cuda:0')


tensor(3, device='cuda:0')

## 6) 텐서의 차원 조작

In [74]:
# 둘 다 똑같이 쓸 수 있음
torch.tensor(np.arange(1, 13).reshape(3, 4))
torch.from_numpy(np.arange(1, 13).reshape(3, 4))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [76]:
t1 = torch.from_numpy(np.arange(1, 13).reshape(3, 4))
t1

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

### .cat() : 기존의 텐서를 연결하는 메서드

In [78]:
# torch.cat([t1, [1, 2, 3]], dim=0)

In [81]:
torch.cat([t1 + t1], dim=0)
# 행에다 추가??행을추가?

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [82]:
torch.cat([t1 , t1], dim=0)
# 열에다 추가? 열을추가..

# 행열을 확장시키고싶을때? 사용............................................?????????????????????

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [84]:
v1 = torch.tensor(range(1, 5))
v1

tensor([1, 2, 3, 4])

In [85]:
v1[2] = 300
v1
# crud가 가능한? 자료구조라? 값 바꿀수잇슨

tensor([  1,   2, 300,   4])

In [86]:
# 하지만 다이렉트로 집어넣으면 원본이 훼손됨

In [88]:
v2 = torch.tensor(range(1, 5))
# .clone() : 원본 배열과 값을 공유하지 않는 복사본을 생성
v3 = v2.clone()
v2

tensor([1, 2, 3, 4])

In [89]:
v3[0] = 1000

print(v2)
print(v3)

tensor([1, 2, 3, 4])
tensor([1000,    2,    3,    4])


In [90]:
v2.reshape(2, 2)

tensor([[1, 2],
        [3, 4]])

In [92]:
v2.view(2, 2)

tensor([[1, 2],
        [3, 4]])

In [94]:
# rand가 뭐고..............
t1 = torch.rand((10, 3, 4))
# 3행 4열 데이터가 10개인 데이터를 만들거임!!
t1

tensor([[[0.9994, 0.1712, 0.6260, 0.6950],
         [0.4221, 0.9839, 0.9004, 0.2278],
         [0.7417, 0.9068, 0.3386, 0.5081]],

        [[0.5840, 0.8555, 0.1162, 0.4215],
         [0.9261, 0.5130, 0.8139, 0.5853],
         [0.6718, 0.9201, 0.4669, 0.3612]],

        [[0.5206, 0.5176, 0.8378, 0.1979],
         [0.2517, 0.6789, 0.6892, 0.4911],
         [0.1099, 0.5195, 0.5917, 0.3775]],

        [[0.2701, 0.7065, 0.5371, 0.2366],
         [0.1541, 0.7854, 0.1286, 0.6363],
         [0.1622, 0.1485, 0.4414, 0.9925]],

        [[0.5809, 0.7100, 0.5993, 0.7263],
         [0.2269, 0.4483, 0.2113, 0.7105],
         [0.0547, 0.1371, 0.4649, 0.2837]],

        [[0.7233, 0.3019, 0.2466, 0.6081],
         [0.1781, 0.0580, 0.2721, 0.0731],
         [0.6845, 0.7177, 0.4689, 0.4683]],

        [[0.4897, 0.0691, 0.1346, 0.8879],
         [0.9460, 0.6876, 0.2367, 0.9688],
         [0.1800, 0.8781, 0.9651, 0.7962]],

        [[0.3438, 0.8222, 0.0573, 0.2216],
         [0.6725, 0.9822, 0.5232, 0.2712

In [95]:
print(t1)
print(t1.shape)

tensor([[[0.9994, 0.1712, 0.6260, 0.6950],
         [0.4221, 0.9839, 0.9004, 0.2278],
         [0.7417, 0.9068, 0.3386, 0.5081]],

        [[0.5840, 0.8555, 0.1162, 0.4215],
         [0.9261, 0.5130, 0.8139, 0.5853],
         [0.6718, 0.9201, 0.4669, 0.3612]],

        [[0.5206, 0.5176, 0.8378, 0.1979],
         [0.2517, 0.6789, 0.6892, 0.4911],
         [0.1099, 0.5195, 0.5917, 0.3775]],

        [[0.2701, 0.7065, 0.5371, 0.2366],
         [0.1541, 0.7854, 0.1286, 0.6363],
         [0.1622, 0.1485, 0.4414, 0.9925]],

        [[0.5809, 0.7100, 0.5993, 0.7263],
         [0.2269, 0.4483, 0.2113, 0.7105],
         [0.0547, 0.1371, 0.4649, 0.2837]],

        [[0.7233, 0.3019, 0.2466, 0.6081],
         [0.1781, 0.0580, 0.2721, 0.0731],
         [0.6845, 0.7177, 0.4689, 0.4683]],

        [[0.4897, 0.0691, 0.1346, 0.8879],
         [0.9460, 0.6876, 0.2367, 0.9688],
         [0.1800, 0.8781, 0.9651, 0.7962]],

        [[0.3438, 0.8222, 0.0573, 0.2216],
         [0.6725, 0.9822, 0.5232, 0.2712

In [97]:
print(t1.shape)
# 3차원 데이터임

#Why?????????
# 각 숫자는 각 차원의 크기< 라네요

torch.Size([10, 3, 4])


### .permute()
- 차원변경

In [102]:
# 맨첨에 4가 오게하고시플떈
t2 = t1.permute(2, 1, 0)
print(t2.shape) # 10열데이터로 모양이 바뀐거임

torch.Size([4, 3, 10])


In [104]:
t3 = torch.randint(low=0, high=10, size=(10, 3, 4))
t3

tensor([[[1, 7, 8, 2],
         [4, 9, 6, 2],
         [3, 1, 1, 1]],

        [[6, 7, 9, 6],
         [6, 7, 7, 0],
         [9, 8, 1, 8]],

        [[2, 3, 4, 4],
         [4, 5, 3, 5],
         [9, 3, 6, 1]],

        [[3, 1, 2, 3],
         [9, 1, 4, 1],
         [2, 7, 0, 5]],

        [[6, 2, 1, 0],
         [5, 3, 1, 2],
         [1, 8, 3, 8]],

        [[0, 7, 3, 0],
         [8, 7, 9, 2],
         [5, 5, 6, 5]],

        [[6, 7, 7, 1],
         [7, 3, 9, 1],
         [4, 2, 1, 0]],

        [[8, 2, 5, 0],
         [4, 1, 0, 4],
         [8, 5, 4, 1]],

        [[8, 8, 7, 5],
         [1, 2, 2, 0],
         [3, 2, 2, 2]],

        [[8, 2, 5, 2],
         [0, 9, 0, 6],
         [7, 0, 9, 1]]])

In [109]:
# 차수를 추가할수있슴
t4 = t3.unsqueeze(0)
t4

print(t3.shape)
print(t4.shape)

torch.Size([10, 3, 4])
torch.Size([1, 10, 3, 4])


In [111]:
t5 = t4.squeeze()
# 다시 되돌아옴 언스퀴즈였던거 스퀴즈로~~

print(t5.shape)

torch.Size([10, 3, 4])


## 자동 미분과 기울기(requires_grad)
### 미분
- 어떤 값(변수)이 아주 조금 바뀔 때, 그에 따라 다른 값이 얼마나 변하는 지 계산하는 방법이다.

$$
\frac{\Delta y}{\Delta x}
$$

이는 x가 변한 만큼 y가 얼마나 변했는지를 나타냅니다.

예를 들어:

$$
x: 2 \rightarrow 3
$$

이면

$$
\Delta x = 1
$$

그리고

$$
y: 4 \rightarrow 7
$$

이면

$$
\Delta y = 3
$$

따라서

$$
\frac{\Delta y}{\Delta x}
=
\frac{3}{1}
=
3
$$

이것을 평균 변화율이라고 합니다.

미분은 변화량을 0에 가깝게 줄였을 때의 변화율을 의미합니다.

$$
\frac{dy}{dx}
=
\lim_{\Delta x \rightarrow 0}
\frac{\Delta y}{\Delta x}
$$

## 순전파 (Forward Pass): out 계산
### 1) 입력 벡터 정의
$$x = [x_1, x_2] = [3.0, 4.0]$$
$$y = [y_1, y_2] = [1.0, 2.0]$$

### 2) z = x + y 연산
각 성분별로 더해져 새로운 2차원 벡터 $z$가 생성됩니다.
$$z_1 = x_1 + y_1 = 3.0 + 1.0 = 4.0$$
$$z_2 = x_2 + y_2 = 4.0 + 2.0 = 6.0$$
$$z = [4.0, 6.0]$$

### 3) out = z.mean() 연산
벡터 $z$의 모든 성분을 더한 뒤 성분의 개수($n=2$)로 나누어 평균을 구합니다.
$$out = \frac{z_1 + z_2}{2} = \frac{4.0 + 6.0}{2} = 5.0$$

## 2. 역전파 (Backward Pass): 미분 계산

`out.backward()`가 호출되면 연쇄 법칙(Chain Rule)에 의해 최종 출력($out$)에 대한 각 입력 성분들의 미분 값(기울기)이 역순으로 계산됩니다.

### 1) out에 대한 z의 편미분
$$out = \frac{1}{2}z_1 + \frac{1}{2}z_2$$
$$\frac{\partial out}{\partial z_1} = 0.5, \quad \frac{\partial out}{\partial z_2} = 0.5$$

### 2) 연쇄 법칙을 통한 최종 미분 계산 (x와 y 기준)
$z_1 = x_1 + y_1$ 이므로 $\frac{\partial z_1}{\partial x_1} = 1$ 입니다. 이를 활용해 최종 미분 값을 구합니다.

* **x에 대한 미분 값:**
  $$\frac{\partial out}{\partial x_1} = \frac{\partial out}{\partial z_1} \times \frac{\partial z_1}{\partial x_1} = 0.5 \times 1 = 0.5$$
  $$\frac{\partial out}{\partial x_2} = \frac{\partial out}{\partial z_2} \times \frac{\partial z_2}{\partial x_2} = 0.5 \times 1 = 0.5$$

* **y에 대한 미분 값 (위와 동일):**
  $$\frac{\partial out}{\partial y_1} = 0.5, \quad \frac{\partial out}{\partial y_2} = 0.5$$

In [125]:
x = torch.tensor([3.0, 4.0], requires_grad=True)
y = torch.tensor([1.0, 2.0], requires_grad=True)

print(x, y)
print(x + y)

# 순전파 
out = (x + y).mean()
print(out)

tensor([3., 4.], requires_grad=True) tensor([1., 2.], requires_grad=True)
tensor([4., 6.], grad_fn=<AddBackward0>)
tensor(5., grad_fn=<MeanBackward0>)


In [128]:
# 역전파
out.backward()
# 꼭 기억하기! 중요한것. 

In [127]:
print(f"x.grad: {x.grad}")
print(f"y.grad: {y.grad}")

x.grad: tensor([0.5000, 0.5000])
y.grad: tensor([0.5000, 0.5000])
